### PR TITLE
Add benchmarks test to CI pipeline

### LINKED ISSUE #97: Add benchmarks to test runs
We are not catching failure to benchmarking tests in CI/CD

Can you please add cargo test --features runtime-benchmarks.

### PR DESCRIPTION
**Pull request by evilrobot-01**
Included benchmarks in test runs.

CI/CD expected to fail due to benchmark issue to be fixed in another PR

### CODE REVIEW

**Comment by stojanov-igor** [comment]
One of the benchmarking tests is failing.

**Comment by stojanov-igor** [comment]
Still getting failed benchmarking test.

`failing benchmark tests:
revive_task: "NoPermissionToRevive"`

@f-gate Can you take a look?

**Comment by evilrobot-01** [comment]
Not sure if you want to merge this to catch the benchmark issues via tests as intended, or fix issues via separate PRs, rebasing this branch until this PR passes and then merge.

**Comment by f-gate** [comment]
I merged universal-develop in and found the error. The state setup was incorrect in the revive benchmark.

**Review by stojanov-igor — APPROVED** [review]
Looks good.

**Pull request merged**
